# Generated by Django 5.0.2 on 2024-03-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_addnewpatient_medicines_alter_addnewpatient_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewpatient',
            name='medicines',
            field=models.CharField(default='Nothing', max_length=200),
        ),
    ]
