# Generated by Django 5.0.2 on 2024-04-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_addnewpatient_medicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addnewpatient',
            name='medicines',
        ),
    ]
